export default {
  app: {},
  candidates: [
    {
      id: 1,
      name: "Per Spelmann",
      emailPriv: "per@mail.no",
      emailGet: "per.spelmann@getacademy.no",
      phoneNumber: "000 00 000",
      discordName: "per.spelmann",
      profilPicture: "../img/per_spelmann.png",
      courses: ["FrontEnd", "StartIT"],
      events: [
        {
          course: "FrontEnd",
          applied: 2025 - 0o1 - 0o1,
          started: 2025 - 0o1 - 0o2,
          completed: false,
          quit: false,
          paymentAdded: 55000,
        },
        {
          course: "StartIT",
          applied: 2024 - 0o1 - 0o1,
          started: 2024 - 0o1 - 0o2,
          completed: false,
          quit: false,
          paymentAdded: 55000,
        },
      ],
    },
    {
      id: 2,
      name: "Petter Nordmann",
      emailPriv: "petter@mail.no",
      emailGet: "petter.nordmann@getacademy.no",
      phoneNumber: "000 00 000",
      discordName: "petter.nordmann",
      profilPicture: "../img/per_spelmann.png",
      events: {
        courses: [],
        applied: new Date(),
        started: false,
        completed: false,
        quit: false,
        paymentAdded: 0,
      },
    },
    {
      id: 3,
      name: "Kari Spelmann",
      emailPriv: "kari@mail.no",
      emailGet: "kari.spelmann@getacademy.no",
      kurs: "FrontEnd",
      kursType: "Fagskole",
      startDato: "2025-08-12",
      sluttdato: null,
      telefonNummer: "000 00 000",
      discordNavn: "kari.spelmann",
      profilBilde: "../img/per_spelmann.png",
      events: {
        courses: [],
        applied: new Date(),
        started: false,
        completed: false,
        quit: false,
        paymentAdded: 0,
      },
    },
  ],
  kurs: [
    {
      id: 1,
      navn: "StartIT",
      pris: 55000,
      events: {},
    },
    {
      id: 2,
      navn: "FrontEnd",
      pris: 55000,
      events: {},
    },
  ],
};
